### PR TITLE
Update Ahune.lua

### PR DESCRIPTION
**Pull request by nanjuekaien1**

### CODE REVIEW

**Review by MysticalOS — CHANGES_REQUESTED** [review]
Changing these why? the way core is coded is dnumber check if instance return exists but if not does a string lookup from locals/name field.

Now I haven't made sure this code didn't break in unified somehow, been really busy with IRL stuff, but if the dnumber stuff isn't doing fallback correctly I'd rather fix that then fragment world event mods more.

TL/DR, just localize names normally but leave the string idenitfier of mods as is.

**Comment by MysticalOS** [comment]
Code, for reference

`		elseif name:match("d%d+") then
			local t = self:GetDungeonInfo(string.sub(name, 2))
			if type(nameModifier) == "number" then--do nothing
			elseif type(nameModifier) == "function" then--custom name modify function
				t = nameModifier(t or name)
			else--default name modify
				t = string.split(",", t or name)
			end
			obj.localization.general.name = t or name`

**Comment by MysticalOS** [comment]
Actually I see the bug now. no idea when this got fucked up, fixing it in core

**Comment by nanjuekaien1** [comment]
DBM

**Comment by MysticalOS** [comment]
I confirmed fix in latest unified core commit, closing this. The dxxx should once again fallback to .name if GetDungeonInfo returns nil.

The order was always meant to be use api, use localized name, fallback to string if first two fail.

**Comment by nanjuekaien1** [comment]
Okay!

**Pull request closed without merging**
