### PR TITLE
make time accurate.

### PR DESCRIPTION
**Pull request by coolaken**
more ran 20sec will not reset time.

### CODE REVIEW

**Comment by MysticalOS** [comment]
better way to code it then this. if that's the rule I can fix that much cleaner

**Comment by coolaken** [comment]
thanks

**Comment by MysticalOS** [comment]
https://github.com/DeadlyBossMods/DBM-TBC-Classic/commit/a9706cb316676da575d9499da4952322a6001ea9 should cover it. it uses built in api to see how much time remaining, if less than 20 it extends EXISTING timer to 20 by appending the time differential to the total, but if time > 20 it won't do anything at all. No additional variables needed.

**Comment by coolaken** [comment]
it's so cool.

**Pull request closed without merging**
