### PR TITLE
Update hyjal wave timer

### PR DESCRIPTION
**Pull request by gwtwind**
L.Jaina and UnitName() is not the same.
eg) Lady jaina Proudmoore vs Jaina Proudmoore

add kr female gossip and fix

### CODE REVIEW

**Review by MysticalOS — CHANGES_REQUESTED** [review]
`elseif selection == L.AzgalorGossip or (L.KazrogalGossipF and selection == L.AzgalorGossipF) then`
this looks like a mistake

**Comment by QartemisT** [comment]
I've fixed the issue regarding the invalid check that MysticalOS pointed out. Rather than changing the logic for jaina/thrall matching, I recommend actually updating the localization for the name instead :)

**Comment by gwtwind** [comment]
> I've fixed the issue regarding the invalid check that MysticalOS pointed out. Rather than changing the logic for jaina/thrall matching, I recommend actually updating the localization for the name instead :)

Updated localization.kr.lua

**Comment by gwtwind** [comment]
Updated localization.kr.lua

**Comment by MysticalOS** [comment]
> I've fixed the issue regarding the invalid check that MysticalOS pointed out. Rather than changing the logic for jaina/thrall matching, I recommend actually updating the localization for the name instead :)

I actually disagree, almost all mods use match AND find, changing it from match to find is wrong, but leaving it as match is also wrong, it should probably do both match and find checks making it more flexible to localizers and more importantly just similar to way most newer mods are laid out..

**Review by MysticalOS — APPROVED** [review]

**Pull request merged**
