### PR TITLE
Fix WaveTimer 

### PR DESCRIPTION
**Pull request by q513902026**
modify widgetID to 3121
API C_GossipInfo.GetOptions is not found ,use GetGossipOptions

### CODE REVIEW

**Comment by MysticalOS** [comment]
Curious why this was closed. was it non working?

**Comment by q513902026** [comment]
this working

**Comment by MysticalOS** [comment]
Ok, well i pushed similar into main repo with better nil checks for safety.

**Comment by q513902026** [comment]
PTR Current Wave Info
```
--[boss] = {waveInfo}
local waveInfo = {
    [1] = {
        -- [waveIndex] = {"NPCId:NPCName:NPCAmount",...}
        [1] = {"17895:Ghoul:10"},
        [2] = {"17895:Ghoul:10", "17897:Fiend:2"},
        [3] = {"17895:Ghoul:6", "17897:Fiend:6"},
        [4] = {
            "17895:Ghoul:6", "17897:Fiend:4",
            "17899:Necromancer:2"
        },
        [5] = {
            "17895:Ghoul:2", "17897:Fiend:6",
            "17899:Necromancer:4"
        },
        [6] = {"17895:Ghoul:6", "17898:Abomination:6"},
        [7] = {"17895:Ghoul:4", "17898:Abomination:4", "17899:Necromancer:4"},
        [8] = {
            "17895:Ghoul:6", "17897:Fiend:4", "17898:Abomination:2",
            "17899:Necromancer:2"
        }
    },
    [2] = {
        [1] = {"17895:Ghoul:10"},
        [2] = {"17895:Ghoul:8", "17898:Abomination:4"},
        [3] = {
            "17895:Ghoul:4", "17897:Fiend:4",
            "17899:Necromancer:4"
        },
        [4] = {
            "17905:Banshee:2", "17897:Fiend:6", "17899:Necromancer:4"
        },
        [5] = {"17905:Banshee:4", "17895:Ghoul:6", "17899:Necromancer:2"},
        [6] = {"17898:Abomination:2", "17895:Ghoul:6", "17899:Necromancer:4"},
        [7] = {
            "17905:Banshee:2", "17898:Abomination:4", "17895:Ghoul:2",
            "17897:Fiend:4"
        },
        [8] = {
            "17905:Banshee:2", "17898:Abomination:4", "17895:Ghoul:4",
            "17899:Necromancer:2", "17897:Fiend:2"
        }
    },
    [3] = {
        [1] = {
            "17905:Banshee:2", "17898:Abomination:4", "17895:Ghoul:6",
            "17899:Necromancer:2"
        },
        [2] = {"17906:Gargoyle:10", "17895:Ghoul:4"},
        [3] = {
            "17897:Fiend:6", "17895:Ghoul:6",
            "17899:Necromancer:2"
        },
        [4] = {
            "17897:Fiend:6", "17906:Gargoyle:6",
            "17899:Necromancer:2"
        },
        [5] = {"17898:Abomination:6", "17895:Ghoul:4", "17899:Necromancer:4"},
        [6] = {"17907:Wyrm:1", "17906:Gargoyle:8"},
        [7] = {"17907:Wyrm:1", "17898:Abomination:4", "17895:Ghoul:6"},
        [8] = {
            "17905:Banshee:2", "17897:Fiend:4", "17898:Abomination:4",
            "17895:Ghoul:4", "17899:Necromancer:2"
        }
    },
    [4] = {
        [1] = {"17898:Abomination:6", "17899:Necromancer:6"},
        [2] = {"17907:Wyrm:1", "17906:Gargoyle:8", "17895:Ghoul:5"},
        [3] = {"17908:Infernal:4", "17895:Ghoul:6"},
        [4] = {"17908:Infernal:5", "17916:Stalker:6"},
        [5] = {
            "17898:Abomination:4", "17916:Stalker:6", "17899:Necromancer:4"
        },
        [6] = {"17905:Banshee:6", "17899:Necromancer:6"},
        [7] = {
            "17908:Infernal:6", "17897:Fiend:2",
            "17916:Stalker:2", "17895:Ghoul:2"
        },
        [8] = {
            "17898:Abomination:4", "17897:Fiend:4", "17916:Stalker:4",
            "17905:Banshee:2", "17899:Necromancer:2"
        }
    }
}
```

**Comment by MysticalOS** [comment]
That wave info matches what dbm has so no changes needed there.

**Comment by q513902026** [comment]
logs 
https://cn.classic.warcraftlogs.com/reports/GCwrPQYKJ9tvLZH2#type=casts&view=events&boss=-3&difficulty=0

**Comment by q513902026** [comment]
’‘’
local table = C_GossipInfo and C_GossipInfo.GetOptions()
‘’‘
C_GossipInfo already exists
so check GetGossipOptions exists.

**Comment by QartemisT** [comment]
Its to provide both Retail and TBC Classic support :)

**Comment by q513902026** [comment]
Retails:
Retails
TBC:
TBC

**Comment by MysticalOS** [comment]
It can be done either way and from a code standpoint still need to get name out of table return anyways so way it is, is fine.

they were supposed to sync apis just never did..they kinda stopped mid way going through them.

**Comment by q513902026** [comment]
fine

**Pull request closed without merging**
